name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  build_and_push:
    runs-on: ubuntu-latest
    needs: build  # Exécute ce job après le job de tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image to Docker Hub
        run: |
          docker build -t yourusername/flaskapp:latest .
          docker push yourusername/flaskapp:latest

      - name: Build and push Docker image to Private Registry
        run: |
          echo "${{ secrets.PRIVATE_REGISTRY_PASSWORD }}" | docker login your-private-registry.com -u "${{ secrets.PRIVATE_REGISTRY_USERNAME }}" --password-stdin
          docker build -t your-private-registry.com/yourusername/flaskapp:latest .
          docker push your-private-registry.com/yourusername/flaskapp:latest

      - name: Send notification email on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.your-email-provider.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Build Failed"
          body: "The build has failed. Please check the logs."
          to: recipient@example.com
          from: sender@example.com